### ISSUE TITLE
A rev dep check that mimics a CRAN-like environment

### ISSUE THREAD

**Issue by ddsjoberg** [Genentech/checked#37]
Just throwing out an idea.

I run rev dep checks for a variety of reasons. One common one is before a CRAN submission. Since I use RStudio/Positron, I use checked in the terminal so I can get the cutest messaging `Rscript -e "checked::check_rev_deps(path = '.')"`. One issue I ran into is that I have the `NOT_CRAN` env variable set to TRUE, so I get reports of errors on tests that explicitly skipped on CRAN (e.g. snapshots).

With that in mind, sometimes I want to know if CRAN is going to complain about my submission only and not the FULL set of results (which are still incredibly helpful in other situations). I can of course use {withr} to temporarily override the env variable, but then it makes the terminal command rather long, e.g. `Rscript -e "withr::with_envvar(list(NOT_CRAN = 'false'), code = checked::check_rev_deps(path = '.'))"`.

This is a minor ivconviencene: just passing along some thoughts while using the tool. Thanks for developing it!!

**Comment by dgkf-roche** [comment]
Thanks @ddsjoberg 

How common is it to set `NOT_CRAN` in your local development environment? I always thought that this was something that `testthat` uses internally, but wasn't likely to be something users would configure themselves. 

Regardless, I agree that we should have a mechanism to run as similarly to CRAN as possible to inform a pre-release. Once the API settles a bit, hopefully it's just a matter or pre-specifying a few parameters. 

Until then, we discussed exposing some parameters to at least make this easier to configure without requiring a `withr` handler.

I think I can safely say this is something we want to support, but we're still deciding on exactly what this workflow should look like. We may hold off on implementation until we learn more about common usage patterns.

**Comment by dgkf-roche** [comment]
I think `testthat` runs as "not cran" by default in interactive sessions.

```r
> Sys.getenv("NOT_CRAN")
[1] ""
> testthat:::on_cran()
[1] FALSE
```

So I don't think there's a need to set your own `NOT_CRAN` environment variable.

Let me know if I'm missing something. This wouldn't be the first time I've totally missed the boat on some best practices.

**Comment by ddsjoberg** [comment]
I think you're seeing FALSE because `on_cran()` assumes you're not CRAN if the code is being run interactively. If you run the same code in a reprex, it thinks it is CRAN because `on_cran()` first checks whether it's interactive, then the status of NOT_CRAN.

``` r
withr::with_envvar(new = list(NOT_CRAN = NULL), code = testthat:::on_cran())
#> [1] TRUE
```

<sup>Created on 2024-09-03 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

I think this would mean that if I were to run my tests locally and not interactively (as we often do), then the check would assume we're on CRAN (unless there is something else going on somewhere that I a unaware of!).

**Comment by dgkf-roche** [comment]
Ah, of course - we're running in a non-interactive child process. 

Thinking more about it, I'm actually a bit surprised that setting the environment variable is having any effect. We use `rcmdcheck` internally, and without passing environment variables through a specific parameter they should be ignored.

Was the `withr` approach working for you to disable the `skip_on_cran()` tests, or was that just a hypothetical?

**Comment by ddsjoberg** [comment]
> Thinking more about it, I'm actually a bit surprised that setting the environment variable is having any effect. We use `rcmdcheck` internally, and without passing environment variables through a specific parameter they should be ignored.

I thought `rcmdcheck()` still used your env variables, but TBH I don't really touch this function outside of the defaults. The `rcmdcheck(env)` doc says to supply a list of _extra_ env variables, which could mean that they do recognize the existing env variables
 
> Was the `withr` approach working for you to disable the `skip_on_cran()` tests, or was that just a hypothetical?

I just saw a failure of a snapshot test, so I knew it wasn't running like it would on CRAN. I didn't actually test that code.

**Comment by dgkf-roche** [comment]
Cool, then in that case I don't think the `withr` option will be a suitable alternative. We'll plan a way to make this work for you.
